### ISSUE TITLE
3.5 Audit and Remediation - Not Working in 10.13.3

### ISSUE THREAD

**Issue by kbareis** [jamfprofessionalservices/CIS-for-macOS-Sierra#6]
When I run the command below I receive nothing back.
`grep -i ttl /etc/asl/com.apple.install | awk -F'ttl=' '{print $2}'`

This is what my com.apple.install log looks like:
`install messages get saved only in /var/log/install.log
[= Facility install] claim only
file /var/log/install.log format='$((Time)(JZ)) $Host $(Sender)[$(PID)]: $Message'`

**Comment by kenglish6** [comment]
Updated with major/minor OS detection and reporting
