### ISSUE TITLE
5.1.4 additional -ls command is returning more than just the file path

### ISSUE THREAD

**Issue by kbareis** [jamfprofessionalservices/CIS-for-macOS-Sierra#8]
When running this command:
`sudo find /Library -type d -perm -2 -ls | grep -v Caches | grep -v Adobe`
You will return something like:
`4308517949        0 drwxrwxrwx    3 root             admin                  96 Feb 28 09:10 /Library/Application Support/regid.2012-02.com.jamfsw
4308522709        0 drwxrwxrwx    3 root             wheel                  96 Feb 28 09:17 /Library/Application Support/JAMF/Composer
4308522710        0 drwxrwxrwx    3 root             wheel                  96 Feb 28 09:17 /Library/Application Support/JAMF/Composer/Sources
4305462489        0 drwxrwxrwx    4 root             wheel                 128 Jan 23 15:06 /Library/Application Support/Microsoft/WebExPlugin
4307247960        0 drwxrwxrwx    4 root             admin                 128 Feb  8 10:22 /Library/Application Support/regid.1986-12.com.adobe
4297204237        0 drwxrwxrwx    3 root             admin                  96 Feb 28 09:08 /Library/Application Support/VMware/VMware Fusion/Shared
4297040430        0 drwxrwxrwx   12 root             wheel                 384 Feb 28 08:52 /Library/Logs/CrashPlan`

However, it appears that the -ls flag is giving us more than what we need (just the file paths). Ex: When I run:
` sudo find /Library -type d -perm -2 | grep -v Caches | grep -v Adobe`
I only get:
`/Library/Application Support/regid.2012-02.com.jamfsw
/Library/Application Support/JAMF/Composer
/Library/Application Support/JAMF/Composer/Sources
/Library/Application Support/Microsoft/WebExPlugin
/Library/Application Support/regid.1986-12.com.adobe
/Library/Application Support/VMware/VMware Fusion/Shared
/Library/Logs/CrashPlan`
Which should be better for the chmod command in the for loop.

**Comment by kenglish6** [comment]
Modified to remove `-ls`
